include $(TOPDIR)/rules.mk

PKG_VERSION:=1.2.3

LUCI_TITLE:=LuCI Support for Momo-X
LUCI_DEPENDS:=+luci-base +momo-x

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
