include $(TOPDIR)/rules.mk

PKG_VERSION:=1.2.3
PKG_RELEASE:=3

LUCI_TITLE:=LuCI Support for Momo-X
LUCI_DEPENDS:=+luci-base
LUCI_EXTRA_DEPENDS:=momo-x

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
