name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-24.10

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: momox
          PACKAGES: momo-x momo-x-subconverter luci-app-momo momo-x-full
          BUILD_LOG: 1
          NO_REFRESH_CHECK: true
          NO_SHFMT_CHECK: true
          V: sc

      - name: upload build diagnostics
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: diagnostics_${{ matrix.arch }}-${{ matrix.branch }}
          path: |
            logs
            bin/packages/${{ matrix.arch }}/momox
          if-no-files-found: ignore

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: momo-x_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/momox
